// Code generated by trpc-go/trpc-go-cmdline v2.6.5. DO NOT EDIT.
// source: keyword.proto

package pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// KeywordServiceService defines service.
type KeywordServiceService interface {
	GetKeyword(ctx context.Context, req *Request) (*Response, error)
}

func KeywordServiceService_GetKeyword_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &Request{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KeywordServiceService).GetKeyword(ctx, reqbody.(*Request))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// KeywordServiceServer_ServiceDesc descriptor for server.RegisterService.
var KeywordServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.keyword.KeywordService",
	HandlerType: ((*KeywordServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.keyword.KeywordService/GetKeyword",
			Func: KeywordServiceService_GetKeyword_Handler,
		},
	},
}

// RegisterKeywordServiceService registers service.
func RegisterKeywordServiceService(s server.Service, svr KeywordServiceService) {
	if err := s.Register(&KeywordServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("KeywordService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedKeywordService struct{}

func (s *UnimplementedKeywordService) GetKeyword(ctx context.Context, req *Request) (*Response, error) {
	return nil, errors.New("rpc GetKeyword of service KeywordService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// KeywordServiceClientProxy defines service client proxy
type KeywordServiceClientProxy interface {
	GetKeyword(ctx context.Context, req *Request, opts ...client.Option) (rsp *Response, err error)
}

type KeywordServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewKeywordServiceClientProxy = func(opts ...client.Option) KeywordServiceClientProxy {
	return &KeywordServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *KeywordServiceClientProxyImpl) GetKeyword(ctx context.Context, req *Request, opts ...client.Option) (*Response, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.keyword.KeywordService/GetKeyword")
	msg.WithCalleeServiceName(KeywordServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("KeywordService")
	msg.WithCalleeMethod("GetKeyword")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &Response{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
